<?php
$customerData = Mage::helper('simplepay')->customerData();

$totalAmount = Mage::helper('checkout/cart')->getQuote()->getGrandTotal();
$currency = Mage::helper('checkout/cart')->getQuote()->getQuoteCurrencyCode();

$storeName = Mage::app()->getStore()->getName();
?>

<script type="text/javascript">
    //<![CDATA[
    function getScript(url, success){
        var head = document.getElementsByTagName("head")[0], done = false;
        var script = document.createElement("script");
        script.src = url;

        // Attach handlers for all browsers
        script.onload = script.onreadystatechange = function(){
            if ( !done && (!this.readyState ||
                this.readyState == "loaded" || this.readyState == "complete") ) {
                done = true;
                success();
            }
        };

        head.appendChild(script);
    }

    function handler() {
        var handler = SimplePay.configure({
            token: processPayment,
            key: '<?php echo Mage::helper('simplepay')->getConfigurations()['public_api_key']; ?>',
            image: '<?php echo Mage::helper('simplepay')->getConfigurations()['image_url']; ?>'
        });

        var description = '<?php echo Mage::helper('simplepay')->getConfigurations()['description']; ?>';
        if (!description) {
            description = '<?php echo $storeName; ?>'
        }

        handler.open(SimplePay.CHECKOUT, {
            email: '<?php echo $customerData['email']; ?>',
            phone: '<?php echo $customerData['telephone']; ?>',
            description: description,
            address: '<?php echo $customerData['street']; ?>',
            postal_code: '<?php echo $customerData['postcode']; ?>',
            city: '<?php echo $customerData['city']; ?>',
            country: '<?php echo $customerData['country_id']; ?>',
            amount: formatAmount(<?php echo $totalAmount; ?>),
            currency: '<?php echo $currency; ?>'
        });
    }

    function formatAmount(amount) {
        var strAmount = amount.toString().split(".");
        var decimalPlaces = strAmount[1] === undefined ? 0 : strAmount[1].length;
        var formattedAmount = strAmount[0];

        if (decimalPlaces === 0) {
            formattedAmount += '00';

        } else if (decimalPlaces === 1) {
            formattedAmount += strAmount[1] + '0';

        } else if (decimalPlaces === 2) {
            formattedAmount += strAmount[1];
        }

        return formattedAmount;
    }

    function processPayment(token) {
        sessionStorage.token = token;
        review.save();
    }

    document.getElementById('simplepay_checkout').addEventListener("click", function() {
        getScript('https://checkout.simplepay.ng/simplepay.js', function() {
            handler();
        });
    });
    //]]>
</script>

<button id="simplepay_checkout" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Place Order with SimplePay')) ?>"
        class="button btn-checkout">
    <span><span><?php echo $this->__('Place Order with SimplePay') ?></span></span>
</button>
